name: sealed_unions
description: Sealed Unions for Dart
version: 3.0.2+2
maintainer: George Medve (@nodinosaur)
authors: 
- Flutter Community <community@flutter.zone>
- George Medve <contact+gh@androidalliance.co.uk>
homepage: https://github.com/fluttercommunity/dart_sealed_unions
documentation:
environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: "^1.3.3"
